---
apiVersion : v1
kind : configMap
metadata :
  name : bankapp-config
data :
DB_HOST : mysqldb
DB_PORT : "3306"

~                                                                                                                                                                                                                  
~                                                                                                                                                                                                                  
~                                                                                                                                                                                                                  
~                                                                                                                                                                                                                  
~                          
